import localFont from 'next/font/local'
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";

const geistSans = localFont({
  src: './fonts/Geist-Regular.woff2',
  variable: "--font-geist-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}